version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    hostname: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=users_management
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306       # <Port exposed> : < MySQL Port running inside container>
    expose:
      - 3306
    volumes:
      - mysql-data:/data/db

# Names our volume
volumes:
  mysql-data:
    driver: local