version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    hostname: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=users_handling
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306       # <Port exposed> : < MySQL Port running inside container>
    expose:
      - 3306
    volumes:
      - mysql-data:/data/db

# MYSQL Workbench
  mysql-workbench:
    image: ghcr.io/linuxserver/mysql-workbench
    hostname: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
# Names our volume
volumes:
  mysql-data:
    driver: local